from fpdf import FPDF
from datetime import datetime

class PDF(FPDF):
    def header(self):
        self.set_fill_color(50, 130, 184)  # Blue header
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "B", 16)
        self.cell(0, 15, "AI Health Report", ln=True, align="C", fill=True)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(169, 169, 169)
        self.cell(0, 10, f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | AI Health Assistant", 0, 0, "C")

def create_pdf(name, symptoms_list):
    pdf = PDF()
    pdf.add_page()

    # User Information Section
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 10, f"Patient Name: {name}", ln=True)
    pdf.ln(5)

    # Symptoms Section
    pdf.set_fill_color(240, 248, 255)  # Light blue box
    pdf.set_draw_color(100, 100, 100)
    pdf.set_line_width(0.5)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Reported Symptoms", ln=True)
    pdf.set_font("Arial", "", 12)

    pdf.set_fill_color(255, 255, 255)
    for symptom in symptoms_list:
        pdf.cell(10)
        pdf.cell(0, 10, f"- {symptom.strip().capitalize()}", ln=True, fill=True)


    pdf.ln(10)

    # Doctor's Note
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Doctor's Note", ln=True)
    pdf.set_font("Arial", "", 12)
    pdf.multi_cell(0, 10, 
        "This report has been auto-generated by the AI Health Assistant.\n"
        "It provides a basic overview of reported symptoms.\n"
        "Please consult a licensed medical professional for a full diagnosis and treatment plan.")

    # Signature
    pdf.ln(15)
    pdf.set_font("Arial", "I", 11)
    pdf.cell(0, 10, "Dr. AI Assistant", ln=True)

    # Save
    filename = f"AI_Health_Report_{name.replace(' ', '_')}.pdf"
    pdf.output(filename)

    return filename
